// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "DataPartition.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::motifPDM;

class DataPartitionHandler : virtual public DataPartitionIf {
 public:
  DataPartitionHandler() {
    // Your initialization goes here
  }

  void startFirstPhase(const int32_t block) {
    // Your implementation goes here
    printf("startFirstPhase\n");
  }

  void setRange(const int32_t startBlock, const int32_t endBlock) {
    // Your implementation goes here
    printf("setRange\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<DataPartitionHandler> handler(new DataPartitionHandler());
  shared_ptr<TProcessor> processor(new DataPartitionProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

