/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "pdm_constants.h"

namespace motifPDM {

const pdmConstants g_pdm_constants;

pdmConstants::pdmConstants() {
}

} // namespace

