/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef pdm_CONSTANTS_H
#define pdm_CONSTANTS_H

#include "pdm_types.h"

namespace motifPDM {

class pdmConstants {
 public:
  pdmConstants();

};

extern const pdmConstants g_pdm_constants;

} // namespace

#endif
